### ISSUE TITLE
Help with motor commands

### ISSUE THREAD

**Issue by profitt33** [wfang2002/Washer-Motor-Control-API#1]
As a novice C coder I am having difficulty deconstructing your string functions. Can you provide a few examples of the actual strings being sent and received to/from the motor control board. In my application I will be using a microcontroller to interface with the controller.

I have been trying to reverse engineer this motor control board for some time now. What you have accomplished is amazing!  Thanks.

**Comment by wfang2002** [comment]
Example packet FYI:

\x02pmp020887\x03k
\x02mpp020887\x03k

\x02pmp08122d\x033
\x02mpp08122d\x033

\x02pmp106e50\x039
\x02mpp106e50\x039

\x02pmp0a5f5a\x038
\x02mpp0a5f5a\x038

**Comment by profitt33** [comment]
Great, thanks!

Now for another question. I am unfamiliar with the String.Format function and can find little information searching the web. Can you also give output examples for these:

```
         string speedHex = String.Format("{0:x4}", (int)(speed*1.2));
         string paramHex = String.Format("{0:x3}", acceleration);

         string dir = direction == Direction.CW ? "r" : "l";
         string cmd = String.Format("pms{2}{0}{1}", speedHex, paramHex, dir);
```

Am I correct in assuming it is something like "pms4321321r" ?

dp

wfang2002 wrote:

**Comment by wfang2002** [comment]
yes you're correct.

**Comment by profitt33** [comment]
Thank you, I was successful in recreating your work. Great job of reverse engineering.
